"""add repository test profile

Revision ID: 352b3ea56d2f
Revises: a814cc370ada
Create Date: 2026-10-03 12:59:44.833793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '352b3ea56d2f'
down_revision: Union[str, Sequence[str], None] = 'a814cc370ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('test_profile', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'test_profile')
    # ### end Alembic commands ###
