"""add code chunk embeddings

Revision ID: 41239b0894ae
Revises: e3ec8bb7e373
Create Date: 2026-09-17 14:27:18.086152

"""
from typing import Sequence, Union

import pgvector
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR

# revision identifiers, used by Alembic.
revision: str = '41239b0894ae'
down_revision: Union[str, Sequence[str], None] = 'e3ec8bb7e373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_chunks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(1024), nullable=True))
    op.add_column('code_chunks', sa.Column('embedding_model', sa.String(128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_chunks', 'embedding_model')
    op.drop_column('code_chunks', 'embedding')
    # ### end Alembic commands ###
