"""add agent task execution fields

Revision ID: 90b303c32c8b
Revises: 7cad936fbdc1
Create Date: 2026-09-21 15:28:42.494101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90b303c32c8b'
down_revision: Union[str, Sequence[str], None] = '7cad936fbdc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_tasks', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agent_tasks', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agent_tasks', sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('agent_tasks', sa.Column('error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_tasks', 'error')
    op.drop_column('agent_tasks', 'result')
    op.drop_column('agent_tasks', 'completed_at')
    op.drop_column('agent_tasks', 'started_at')
    # ### end Alembic commands ###
