"""create test runs table

Revision ID: 96e3253363ab
Revises: a4c79bcfee0d
Create Date: 2026-10-01 15:23:09.482627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96e3253363ab'
down_revision: Union[str, Sequence[str], None] = 'a4c79bcfee0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('timed_out', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=False),
    sa.Column('stderr', sa.Text(), nullable=False),
    sa.Column('stdout_truncated', sa.Boolean(), nullable=False),
    sa.Column('stderr_truncated', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.CheckConstraint("(status = 'running' AND completed_at IS NULL)OR(status IN ('finished', 'error') AND completed_at IS NOT NULL)", name='ck_test_runs_completion'),
    sa.CheckConstraint("status IN ('running', 'finished', 'error')", name='ck_test_runs_status'),
    sa.CheckConstraint('timeout_seconds > 0', name='ck_test_runs_timeout_positive'),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_runs_task_id'), 'test_runs', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_runs_task_id'), table_name='test_runs')
    op.drop_table('test_runs')
    # ### end Alembic commands ###
