"""add snapshot hash to test runs

Revision ID: a814cc370ada
Revises: 96e3253363ab
Create Date: 2026-10-02 13:44:48.697030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a814cc370ada'
down_revision: Union[str, Sequence[str], None] = '96e3253363ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_runs', sa.Column('snapshot_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_runs', 'snapshot_hash')
    # ### end Alembic commands ###
