"""add task plan review fields

Revision ID: f94a414e578d
Revises: c63d71cd08df
Create Date: 2026-09-25 00:17:51.533077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94a414e578d'
down_revision: Union[str, Sequence[str], None] = 'c63d71cd08df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_tasks', sa.Column('review_decision', sa.String(length=16), nullable=True))
    op.add_column('agent_tasks', sa.Column('review_comment', sa.Text(), nullable=True))
    op.add_column('agent_tasks', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    op.create_check_constraint(
        "ck_agent_tasks_review_decision",
        "agent_tasks",
        "review_decision IS NULL "
        "OR review_decision IN ('approved', 'rejected')",
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_tasks', 'reviewed_at')
    op.drop_column('agent_tasks', 'review_comment')
    op.drop_column('agent_tasks', 'review_decision')
    # ### end Alembic commands ###
